# Generated by Django 4.2.7 on 2023-11-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='confirm',
        ),
    ]
