# Generated by Django 4.2.7 on 2023-11-18 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='choice',
            new_name='Special_Instructions',
        ),
    ]
