# Generated by Django 4.2.7 on 2023-11-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howdy', '0002_rename_choice_order_special_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
